version: 0.2

phases:
  pre_build:
    commands:
      - printenv
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - aws ecr create-repository --region ${AWS_DEFAULT_REGION} --repository-name ${APPLICATION_NAME} &
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $APPLICATION_NAME:$CODEBUILD_WEBHOOK_TRIGGER .
      - docker tag $APPLICATION_NAME:$CODEBUILD_WEBHOOK_TRIGGER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$CODEBUILD_WEBHOOK_TRIGGER      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APPLICATION_NAME:$CODEBUILD_WEBHOOK_TRIGGER