version: 0.2

phases:
  pre_build:
    commands:
      - printenv
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - BUILD_IMAGE=${APPLICATION_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - aws ecr create-repository --region ${AWS_DEFAULT_REGION} --repository-name ${APPLICATION_NAME} &
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $BUILD_IMAGE .
      - docker tag $BUILD_IMAGE $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BUILD_IMAGE
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${BUILD_IMAGE}
      - DOCKER_IMAGE= ${AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$BUILD_IMAGE}
      - echo Writing image definitions file...
      - sed -i.bak  -e "s;%IMAGE%;${DOCKER_IMAGE};g" fargate-task.json
artifacts:
    files: fargate-task.json